### ISSUE TITLE
微信小程序 import * as sentry from "sentry-mina"全量引入，导致文件过大 

### ISSUE THREAD

**Issue by Roat** [alexayan/sentry-mina#10]
微信小程序全量引入sentry-mina，会额外增加900多k，导致文件过大，有没有局部引入的方式，比如按需引用，或者在其他项目中全量导入时是如何解决文件过大问题呢？

**Comment by alexayan** [comment]
https://github.com/alexayan/sentry-mina/blob/master/browser/sentry-mina.js
打包后的尺寸最多不超过 100 K，虽然还有优化的空间，但不会有 900K 这么多
