### ISSUE TITLE
sentry.captureException调用失效

### ISSUE THREAD

**Issue by Roat** [alexayan/sentry-mina#11]
如果把sentry.captureException放在wx.uploadFile接口调用失败的回调函数fail()函数体内，后台看不到有日志被记录，通过调试确定fail()函数体内被执行了。如果把sentry.captureException放在success或者complete函数体内，能够看到日志被记录。
另外真机调试时，fail()函数体被执行，能看到真机调试界面输出如下图信息，怎么直接把信息输出到后台呢？
![image](https://user-images.githubusercontent.com/10206718/63490555-8cc94180-c4e7-11e9-8f5f-70141a415721.png)

期望结果：
把sentry.captureException放在fail()函数体内，后台能够看到日志信息。如何把图中错误信息直接输出到后台

**Comment by Roat** [comment]
更正一下：应该是在微信开发者工具调试时调用有效，但是真机调试时调用失败，真机调试时无论放在哪里都没有执行成功

**Comment by Roat** [comment]
import * as sentry from "sentry-mina/browser/sentry-mina.js"是不是这样导入有问题，需要全量导入呢？全量导入文件又过大

**Comment by alexayan** [comment]
> 微信开发者工具调试时调用有效，但是真机调试时调用失败

这个很可能是 sentry 上报的 request 安全域名没有配

**Comment by Roat** [comment]
开发者工具没有勾选“不校验合法域名”，并且可正常使用，说明安全域名配置是没有问题的

**Comment by alexayan** [comment]
> 开发者工具没有勾选“不校验合法域名”，并且可正常使用，说明安全域名配置是没有问题的

可以提供下小程序代码片段吗

**Comment by Roat** [comment]
可以的。非常感谢
（由于在内网开发，无法直接上传代码截图）

小程序使用mpvue
1.引入方式：在main.js使用import * as sentry from "sentry-mina/browser/sentry-mina.js"
2.配置：在main.js：
初始化：
sentry.init({
  dsn: '后台配置的dsn'
})
设置对应tag：
sentry.configureScope(scope => {
      scope.setUser({ id: account });
    });
定义全局：
Vue.prototype.$sentry = sentry
3.在其他需要输出日志的地方使用this.$sentry.captureException(),比如在wx.uploadFile的回调函数体内调用

以上，在开发者工具测试时，能看到日志被记录，但是真机调试时没有日志信息

**Comment by alexayan** [comment]
> 以上，在开发者工具测试时，能看到日志被记录，但是真机调试时没有日志信息

真机调试时看下 network 面板有没有 sentry 的请求发出

**Comment by Roat** [comment]
真机调试时，network面板没看到有sentry的请求发出。但是开发者工具调试时可以看到
![image](https://user-images.githubusercontent.com/10206718/63660239-1b8bd600-c7e8-11e9-9ae2-4c67a4916b7d.png)

**Comment by alexayan** [comment]
使用 `mpvue/mpvue-quickstart`, 按照你给的流程，在真机调试时，`captureException`  后台可以正常收到异常日志。

本地设置需要开启增强编译，不然控制台会有报错 `regeneratorRuntime is not defined`

**Comment by Roat** [comment]
![image](https://user-images.githubusercontent.com/10206718/63843796-8fc9a380-c9b9-11e9-87f2-f248b9ec12b9.png)
本地已开启增强编译，真机调试时会有这个报错。
改用raven-weapp这个包，真机调试时后台能收到日志，但不是每一次都能收到，还没找到原因

**Comment by alexayan** [comment]
> ![image](https://user-images.githubusercontent.com/10206718/63843796-8fc9a380-c9b9-11e9-87f2-f248b9ec12b9.png)
> 本地已开启增强编译，真机调试时会有这个报错。
> 改用raven-weapp这个包，真机调试时后台能收到日志，但不是每一次都能收到，还没找到原因

没遇到过这个错误， `import * as sentry from "sentry-mina` 这样导入试试

**Comment by alexayan** [comment]
修复了，麻烦尝试安装 sentry-mina@0.3.0 测试下，感谢 :)

**Comment by Roat** [comment]
问题解决了，太给力了，赞
