### ISSUE TITLE
使用第三方插件时会报错

### ISSUE THREAD

**Issue by wusb** [alexayan/sentry-mina#16]
[non-writable] modification of global variable "Function.prototype.toString" is not allowed when using plugins at app.json.

**Comment by alexayan** [comment]
init 方法中配置 defaultIntegrations 可以临时解决解决这个错误

```javascriptt
Sentry.init({
  defaultIntegrations: []
});
```

**Comment by wusb** [comment]
这样配置对现有功能有什么影响吗？

**Comment by alexayan** [comment]
对错误上报没有任何影响，只是会禁用一些插件

默认配置是这个

```
export const defaultIntegrations = [
  new CoreIntegrations.Dedupe(),
  new CoreIntegrations.InboundFilters(),
  new CoreIntegrations.FunctionToString(),
  new GlobalHandlers(),
  new LogManager()
];
```

`new CoreIntegrations.FunctionToString() ` 这个中间件在插件环境中会出错，只要不配置它就行

你的项目中可以配置，启用部分插件

```javascript
Sentry.init({
  defaultIntegrations: [
     new Sentry.Integrations.Dedupe(),
    new Sentry.Integrations.InboundFilters(),
    new Sentry.Integrations.GlobalHandlers(),
    new Sentry.Integrations.LogManager()
 ]
});
```

**Comment by wusb** [comment]
好的，谢谢解答

**Comment by alexayan** [comment]
`[non-writable] modification of global variable "Function.prototype.toString" is not allowed when using plugins at app.json.` 这个报错也不会对程序核心功能有任何影响，可以选择忽略。
