### ISSUE TITLE
对错误上报没有任何影响，只是会禁用一些插件

### ISSUE THREAD

**Issue by monw3c** [alexayan/sentry-mina#17]
对错误上报没有任何影响，只是会禁用一些插件

默认配置是这个

```
export const defaultIntegrations = [
  new CoreIntegrations.Dedupe(),
  new CoreIntegrations.InboundFilters(),
  new CoreIntegrations.FunctionToString(),
  new GlobalHandlers(),
  new LogManager()
];
```

`new CoreIntegrations.FunctionToString() ` 这个中间件在插件环境中会出错，只要不配置它就行

你的项目中可以配置，启用部分插件

```javascript
Sentry.init({
  defaultIntegrations: [
     new Sentry.Integrations.Dedupe(),
    new Sentry.Integrations.InboundFilters(),
    new Sentry.Integrations.GlobalHandlers(),
    new Sentry.Integrations.LogManager()
 ]
});
```

_Originally posted by @alexayan in https://github.com/alexayan/sentry-mina/issues/16#issuecomment-572439617_

这样会报错：
Sentry.Integrations.Dedupe is not a function
TypeError: Sentry.Integrations.Dedupe is not a function

**Comment by alexayan** [comment]
你安装的 sentry-mina 是哪个版本？
控制台打印下 Sentry.Integrations 对象

**Comment by monw3c** [comment]
version: 0.9.1

Sentry.Integrations 对象:
![image](https://user-images.githubusercontent.com/1715568/75106480-1ead3500-5658-11ea-9daa-f9cb4928668a.png)

**Comment by alexayan** [comment]
> version: 0.9.1
> 
> Sentry.Integrations 对象:
> ![image](https://user-images.githubusercontent.com/1715568/75106480-1ead3500-5658-11ea-9daa-f9cb4928668a.png)

`sentry-mina` 目前的最新版本是 `0.4.3`，请检查下你使用的 npm 模块是否是 `sentry-mina`
