### ISSUE TITLE
TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by monw3c** [alexayan/sentry-mina#18]
![image](https://user-images.githubusercontent.com/1715568/75315915-f3685700-589e-11ea-9ba4-c6fdde74a602.png)

**Comment by alexayan** [comment]
当前项目是 `sentry-mina`，你使用的库是 `sentry-miniapp`，这是两个不同的项目

**Comment by monw3c** [comment]
不是的，我把sentry-mina包的替换到到这个文件里了，只是名字没改

**Comment by alexayan** [comment]
可以提供可以复现问题的小程序代码片短吗

https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by monw3c** [comment]
抱歉，排查是组员导入错误所致
