### ISSUE TITLE
npm 构建报错，dependencies里的依赖包@babel/runtime，package没有指定main,也没有index.js，是否可以把这个依赖放到devDependencies中？避免每次构建报错

### ISSUE THREAD

**Issue by WormGirl** [alexayan/sentry-mina#24]
![image](https://user-images.githubusercontent.com/16078260/91274208-ede9bc00-e7b0-11ea-967e-575b3ce408e2.png)

**Comment by alexayan** [comment]
1. package.json 中有 `main` 字段。
2. 目前不支持小程序开发工具的 npm 包构建。
3. 对于使用了小程序原生 npm 包构建的项目，在通过 npm 安装后，可以将 dist/sentry-mina.js 文件手动复制进项目中。

**Comment by WormGirl** [comment]
> 1. package.json 中有 `main` 字段。
> 2. 目前不支持小程序开发工具的 npm 包构建。
> 3. 对于使用了小程序原生 npm 包构建的项目，在通过 npm 安装后，可以将 dist/sentry-mina.js 文件手动复制进项目中。

@babel/runtime是这个依赖包没有main字段

**Comment by alexayan** [comment]
> > 1. package.json 中有 `main` 字段。
> > 2. 目前不支持小程序开发工具的 npm 包构建。
> > 3. 对于使用了小程序原生 npm 包构建的项目，在通过 npm 安装后，可以将 dist/sentry-mina.js 文件手动复制进项目中。
> 
> @babel/runtime是这个依赖包没有main字段

抱歉，没仔细看你提的问题就依据以往的经验做了回答。查了下官方文档[https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html) ，目前是可以通过你提到的方式进行修改，以支持在开发工具中进行 npm 构建。

**Comment by alexayan** [comment]
在 npm 版本 0.4.6 中进行了修复。

**Comment by WormGirl** [comment]
> 在 npm 版本 0.4.6 中进行了修复。

谢谢👍👍👍
