### ISSUE TITLE
面包屑里为什么没有console日志

### ISSUE THREAD

**Issue by abc3971139** [alexayan/sentry-mina#25]
`new sentry.Integrations.Breadcrumbs({
            console: ['log', 'info', 'warn', 'error'],})` 
console已设置为记录所有日志，但是面包屑里没有console

**Comment by alexayan** [comment]
能否提供更多的信息（ sentry-mina 版本，代码运行环境）

**Comment by alexayan** [comment]
> `new sentry.Integrations.Breadcrumbs({ console: ['log', 'info', 'warn', 'error'],})`
> console已设置为记录所有日志，但是面包屑里没有console

能否提供更多的信息（ sentry-mina 版本，代码运行环境）

**Comment by abc3971139** [comment]
> 运行代码
```javascript
  import * as sentry from 'sentry-mina';
  sentry.init({
    dsn: 'DSN地址',
    minaContext: wx
  });
```
>Taro框架 react运行环境，package.json 部分代码
```
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.0.5",
    "@tarojs/react": "3.0.5",
    "@tarojs/runtime": "3.0.5",
    "@tarojs/taro": "3.0.5",
    "flyio": "^0.6.14",
    "mobx": "^5.15.4",
    "mobx-react": "^6.2.2",
    "qs": "^6.9.4",
    "react": "^16.10.0",
    "react-dom": "^16.10.0",
    "sentry-mina": "^0.4.6",
    "taro-ui": "3.0.0-alpha.3"
  }
```

**Comment by alexayan** [comment]
在 ` import * as sentry from 'sentry-mina';` 前面添加下述代码就能解决没有 console 日志问题。
```
if (typeof window !== 'undefined' && !window.console) {
   window.console = console;
}
```

目前没空去细查查明是微信基础库还是 taro 的问题。

**Comment by alexayan** [comment]
sentry-mina@0.4.7 进行了修复。
