### ISSUE TITLE
使用最新版微信开发工具开启代码保护功能上传出错

### ISSUE THREAD

**Issue by dalphyx** [alexayan/sentry-mina#26]
使用最新版0.4.6开启代码保护功能出错，看到issues有人反映已经解决，不过我正常引入编译上传后仍然出错。

**Comment by alexayan** [comment]
新版本开发工具出现的问题。测试了很多 npm 库都会出现这个问题。
你在项目中使用 https://github.com/alexayan/sentry-mina/blob/master/sentry-mina-full.js 这个试试。

**Comment by dalphyx** [comment]
安装的包里不包含sentry-mina-full.js，应该需要修改下package的文件设置，重新发布一下:)

**Comment by alexayan** [comment]
sentry-mina-full.js 是未经过压缩和混淆后的版本，用于尝试解决微信代码保护的冲突，并不涉及 bug 修复和功能更新。
使用时，将文件复制进项目中即可使用。
