### ISSUE TITLE
error: "Unable to find authentication information"

### ISSUE THREAD

**Issue by rapRabbit** [alexayan/sentry-mina#4]
RT
错误401 怎么解决呢

**Comment by alexayan** [comment]
> RT
> 错误401 怎么解决呢

检查下是否配置了正确的 Client Keys (DSN)

**Comment by rapRabbit** [comment]
DSN没问题的

**Comment by alexayan** [comment]
检查下 sentry 服务器版本是否是最新版

**Comment by rapRabbit** [comment]
我用的是Raven.js, 会有什么不一样吗

**Comment by alexayan** [comment]
> Raven.js 3.6 requires Sentry server 8.6.0 or later
> Raven.js 2.0 requires Sentry server 8.0.0 or later

https://github.com/getsentry/sentry-javascript/tree/master/packages/raven-js

**Comment by rapRabbit** [comment]
用的是你发的连接里面的dist下面的 raven-js@3.27.0的

**Comment by rapRabbit** [comment]
{error: "Unable to find authentication information"}
官方文档找到这个, https://docs.sentry.io/api/auth/
但是看不懂, 用postman调报错的接口加上token也不行, 请问能给我点思路吗

**Comment by alexayan** [comment]
> {error: "Unable to find authentication information"}
> 官方文档找到这个, https://docs.sentry.io/api/auth/
> 但是看不懂, 用postman调报错的接口加上token也不行, 请问能给我点思路吗

1. 你调用的哪个接口
2. 可以尝试使用 https://github.com/getsentry/sentry-javascript/tree/master/packages/browser 替代 raven-js

**Comment by rapRabbit** [comment]
https://report.url.cn/sentry/api/1355/store/?project=1355  请求的这个接口

**Comment by alexayan** [comment]
> https://report.url.cn/sentry/api/1355/store/?project=1355 请求的这个接口

https://report.url.cn/sentry/api/1355/store/?project=1355&sentry_key=xxxxxx&sentry_version=xxx querystring 中有其他参数吗

**Comment by rapRabbit** [comment]
https://report.url.cn/sentry/api/1355/store/?project=1355&logger=javascript&platform=javascript&message=%E7%9B%91%E6%8E%A7%E5%BC%80%E5%90%AF&stacktrace=%7B%22frames%22%3A%5B%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2Fappservice%3Ft%3D1560342153657%22%2C%22lineno%22%3A2339%2C%22colno%22%3A20%2C%22function%22%3A%22HTMLScriptElement.script.onload%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2Fappservice%3Ft%3D1560342153657%22%2C%22lineno%22%3A2327%2C%22colno%22%3A21%2C%22function%22%3A%22HTMLScriptElement.scriptLoaded%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22%3Canonymous%3E%22%2C%22lineno%22%3A1%2C%22colno%22%3A1%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2F__dev__%2FWAService.js%22%2C%22lineno%22%3A19%2C%22colno%22%3A7304%2C%22function%22%3A%22require%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2Fapp.js%22%2C%22lineno%22%3A10%2C%22colno%22%3A1%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2F__dev__%2FWAService.js%22%2C%22lineno%22%3A18%2C%22colno%22%3A12486%2C%22function%22%3A%22%3F%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2F__dev__%2FWAService.js%22%2C%22lineno%22%3A19%2C%22colno%22%3A1537%2C%22function%22%3A%22Function.%3Canonymous%3E%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2F__dev__%2FWAService.js%22%2C%22lineno%22%3A19%2C%22colno%22%3A1048%2C%22function%22%3A%22new%20e%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2F__dev__%2FWAService.js%22%2C%22lineno%22%3A18%2C%22colno%22%3A31681%2C%22function%22%3A%22e.o%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2Fapp.js%22%2C%22lineno%22%3A29%2C%22colno%22%3A14%2C%22function%22%3A%22e.onLaunch%22%2C%22in_app%22%3Atrue%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2Fverify_mpsdk%2Futils%2Fraven-weapp%2Fraven.js%22%2C%22lineno%22%3A625%2C%22colno%22%3A27%2C%22function%22%3A%22Raven.captureException%22%2C%22in_app%22%3Afalse%7D%2C%7B%22filename%22%3A%22http%3A%2F%2F127.0.0.1%3A29459%2Fappservice%2Fverify_mpsdk%2Futils%2Fraven-weapp%2Fraven.js%22%2C%22lineno%22%3A689%2C%22colno%22%3A21%2C%22function%22%3A%22Raven.captureMessage%22%2C%22in_app%22%3Afalse%7D%5D%7D&fingerprint=%5B%22%E7%9B%91%E6%8E%A7%E5%BC%80%E5%90%AF%22%5D&extra=%7B%22session%3Aduration%22%3A21%7D&breadcrumbs=%7B%22values%22%3A%5B%7B%22timestamp%22%3A1560342154.232%2C%22category%22%3A%22sentry%22%2C%22message%22%3A%22%E7%9B%91%E6%8E%A7%E5%BC%80%E5%90%AF%22%2C%22event_id%22%3A%2225eba8df19a7485eaeb607590738e08c%22%2C%22level%22%3A%22error%22%7D%5D%7D&environment=production&release=1.0.1&event_id=c17b6143685349faabaaa1f9735875e2
完整的地址,没有sentry_key&sentry_version

**Comment by alexayan** [comment]
确认下是否正确初始化，DSN 格式是否正确

 ```Raven.config('https://<key>@sentry.io/<project>').install()```

**Comment by rapRabbit** [comment]
这句初始化直接在接入引导里拷下来的,没问题QAQ

**Comment by alexayan** [comment]
> 这句初始化直接在接入引导里拷下来的,没问题QAQ

没用过 Raven.js，目前毫无办法。你去 https://github.com/getsentry/sentry-javascript 问问
