### ISSUE TITLE
新人求教：INTEGRATIONS里的函数该怎么用

### ISSUE THREAD

**Issue by xmsz** [alexayan/sentry-mina#5]
直接new Sentry.Integrations.TryCatch();？还有需要什么时候调用

**Comment by alexayan** [comment]
https://docs.sentry.io/error-reporting/configuration/?platform=browser#integration-configuration

```javascript
Sentry.init({
  integrations: [
    new Sentry.Integrations.TryCatch()
  ]
});
```

**Comment by xmsz** [comment]
ok 明白了， 最后一个疑问，作为萌新这些有呢些是一定要开的吗？或者推荐开哪些，他们有什么影响不

**Comment by iShuhao12138** [comment]
默认的GlobalHandlers是开启的，如何关闭此项功能；
我在init中
sentry.init({
      ...params,
      integrations: [
        // 面包屑的记录内容
        new sentry.Integrations.Breadcrumbs({
          console: true,
          request: true,
          navigation: true,
          api: true,
          lifecycle: true
        }),
        // 捕获并记录 setTimeout, setInterval 内的异常
        new sentry.Integrations.TryCatch(),
        // 将 Sentry 事件数据记录到小程序 LogManager
        new sentry.Integrations.LogManager({ level: 0 })
      ]
    })
但是sentry还是默认上报了onError的错误

**Comment by alexayan** [comment]
> 默认的GlobalHandlers是开启的，如何关闭此项功能；
> 我在init中
> sentry.init({
> ...params,
> integrations: [
> // 面包屑的记录内容
> new sentry.Integrations.Breadcrumbs({
> console: true,
> request: true,
> navigation: true,
> api: true,
> lifecycle: true
> }),
> // 捕获并记录 setTimeout, setInterval 内的异常
> new sentry.Integrations.TryCatch(),
> // 将 Sentry 事件数据记录到小程序 LogManager
> new sentry.Integrations.LogManager({ level: 0 })
> ]
> })
> 但是sentry还是默认上报了onError的错误

```
sentry.init({
  defaultIntegrations: false, // 禁用所有默认的 Integrations
  integrations: [] // 配置自定义 Integrations
})
```

**Comment by alexayan** [comment]
> ok 明白了， 最后一个疑问，作为萌新这些有呢些是一定要开的吗？或者推荐开哪些，他们有什么影响不

默认就开启了所有 Integrations，不需要额外配置。

**Comment by xmsz** [comment]
那对性能会有什么影响不，因为我们小程序用户的手机都是比较低端的

**Comment by iShuhao12138** [comment]
好的，多谢

**Comment by alexayan** [comment]
> 低端

不会影响性能

**Comment by xmsz** [comment]
ok! 感谢
