### ISSUE TITLE
sentry.captureMessage

### ISSUE THREAD

**Issue by AzubuFrost** [alexayan/sentry-mina#6]
在相同页面上captureMessage，message值为固定时，只能发出一次请求，以后请求发不出去

**Comment by AzubuFrost** [comment]
期望结果：可以在调用函数的时候调用captureMessage并向sentry服务端发送消息
实际结果：相同message在当前页面只能发送一次，第二次会被忽略，查看XHR无请求发送

**Comment by alexayan** [comment]
> 期望结果：可以在调用函数的时候调用captureMessage并向sentry服务端发送消息
> 实际结果：相同message在当前页面只能发送一次，第二次会被忽略，查看XHR无请求发送

https://docs.sentry.io/platforms/javascript/#dedupe

默认配置中有 Sentry.Integrations.Dedupe，会过滤重复的事件

```
sentry.init({
  defaultIntegrations: false
})
```

禁用所有默认的 Integrations

**Comment by alexayan** [comment]
#5
