### ISSUE TITLE
Uncaught错误获取

### ISSUE THREAD

**Issue by benjamin-pan** [alexayan/sentry-mina#8]
Uncaught (in promise) TypeError: a.split is not a function这种错误只能在try{}catch(){}里面获取吗？

**Comment by alexayan** [comment]
你这个是 promise 内抛出的异常，可以通过 promise.catch(err => {}) 进行捕获

**Comment by alexayan** [comment]
sentry-mina 也会根据 console 中的日志信息判断是否有未捕获的异常，并进行上报

**Comment by benjamin-pan** [comment]
我为了测试是否接入成功，特地写错语法。源码是let a=123;a.split('.');在开发这工具报了：index.js:60 Uncaught (in promise) TypeError: a.split is not a function
但是我在onError中没有获取到，当然在try catch中能获取到错误。所以我想确认一下，这中语法错误是否只能try catch还是有别的办法。请指点。

**Comment by alexayan** [comment]
> 我为了测试是否接入成功，特地写错语法。源码是let a=123;a.split('.');在开发这工具报了：index.js:60 Uncaught (in promise) TypeError: a.split is not a function
> 但是我在onError中没有获取到，当然在try catch中能获取到错误。所以我想确认一下，这中语法错误是否只能try catch还是有别的办法。请指点。

只能 try catch

**Comment by benjamin-pan** [comment]
xie xie

> > 我为了测试是否接入成功，特地写错语法。源码是let a=123;a.split('.');在开发这工具报了：index.js:60 Uncaught (in promise) TypeError: a.split is not a function
> > 但是我在onError中没有获取到，当然在try catch中能获取到错误。所以我想确认一下，这中语法错误是否只能try catch还是有别的办法。请指点。
> 
> 只能 try catch

好的，谢谢。

**Comment by benjamin-pan** [comment]
> > 我为了测试是否接入成功，特地写错语法。源码是let a=123;a.split('.');在开发这工具报了：index.js:60 Uncaught (in promise) TypeError: a.split is not a function
> > 但是我在onError中没有获取到，当然在try catch中能获取到错误。所以我想确认一下，这中语法错误是否只能try catch还是有别的办法。请指点。
> 
> 只能 try catch

好的，谢谢。
